let showSummary = document.getElementById("summary");
let list = document.createElement("ul");
let firstName = localStorage.getItem("firstName")
let lastName = localStorage.getItem("lastName")
let phone = localStorage.getItem("phone")
let email = localStorage.getItem("email")
let address = localStorage.getItem("address")
let country = localStorage.getItem("country")
let state = localStorage.getItem("state")
let city = localStorage.getItem("city")
document.getElementById("firstName").innerText = `First name: ${firstName}`;
document.getElementById("lastName").innerText = `Last name: ${lastName}`;
document.getElementById("phone").innerText = `Phone number: ${phone}`;
document.getElementById("email").innerText = `Email: ${email}`;
document.getElementById("address").innerText = `Address: ${address}`;
document.getElementById("country").innerText = `Country: ${country}`;
document.getElementById("state").innerText = `State: ${state}`;
document.getElementById("city").innerText = `City: ${city}`;
